name: Python package

on:
  push: # 推送时触发工作流
    branches: [ "main" ]

# 具体任务
jobs: 
  build: # 任务名称
    name: start build # 工作名称
    runs-on: windows-latest # 系统镜像
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"] # 指定python版本

    steps: # 具体步骤
    - uses: actions/checkout@v3 # 进入该项目目录
    - name: Set up Python ${{ matrix.python-version }} # 步骤名
      uses: actions/setup-python@v3 # 安装python
      with: # 完成后执行
        python-version: ${{ matrix.python-version }} # 查看python版本
    - name: Install dependencies  # 步骤名
      run: | # 安装依赖
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Deploy infinity # 步骤名
      run: | # 打包应用
        pyside6-deploy main.py


